name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # or master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Docker Image
        run: |
          docker build -t yourdockerhubusername/mean-backend:latest ./backend

      - name: Build Frontend Docker Image
        run: |
          docker build -t yourdockerhubusername/mean-frontend:latest ./frontend

      - name: Push Backend Image
        run: docker push yourdockerhubusername/mean-backend:latest

      - name: Push Frontend Image
        run: docker push yourdockerhubusername/mean-frontend:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /path/to/your/project
            docker-compose pull
            docker-compose up -d
